global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "credit-risk-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: "credit-risk-consumer"
    metrics_path: /metrics
    static_configs:
      - targets: ["consumer:9101"]
